### ISSUE TITLE
how does a struct saved by the zoom

### ISSUE THREAD

**Issue by xiaoao** [albrow/zoom#7]
set, hash, or list? and  how can I get it by redis-cli?

**Comment by albrow** [comment]
Great question.

All the fields for the struct are stored in a hash with the key `<modelName>:<id>`. All primitive fields (int, bool, string, byte, rune, etc) are converted to strings. Everything else falls back to a binary encoding via the gob package.

When you call Save, the model's id is also added to a set of all ids for a given type. The key for the set is `<modelName>:all`.

Lastly if you add the `zoom:"index"` struct tag to any of the fields they will be saved in a sorted set with the key `<modelName>:<fieldName>`. These sorted set indexes are used to do queries.

Here's a concrete example. Let's say you have a Person type:

``` go
type Person struct {
    Name string
    Age  int         `zoom:"index"`
    zoom.DefaultData
}
```

And you create and save a new person like so:

``` go
person := &Person{
    Name: "Bob",
    Age: 27,
}
if err := zoom.Save(person); err != nil {
    // handle err
}
```

When you call Save, a random id will be generated for the model. For the sake of simplicity let's say the id that was generated was "foo". Here are the redis commands that will be run:

``` bash
# Add the fields to the main model hash
HMSET Person:foo Name Bob Age 27
# Add the model id to the set of all person ids
SADD Person:all foo
# Index the Age field in a sorted set
ZADD Person:Age 27 foo
```

Note that I left out string indexes because those are a bit more complicated. However, I'm happy to share if you are curious.

In order to get the fields for the model from redis, you need to know the id. In the above example, you could use `HGETALL Person:foo`. If you don't know the id, you can check the set of all ids. In the above example, this would be `SMEMBERS Person:all`.

Let me know if you have any other questions. Otherwise, I will add all this information to the documentation and then close this issue.

**Comment by albrow** [comment]
By the way, in the [rewrite branch](https://github.com/albrow/zoom/blob/rewrite/model_type.go#L108) there are methods to get all the keys that are used for storing a model in Redis. I'm not sure when I will be able to merge it into master, but I'm working on the rewrite branch almost every day.

**Comment by xiaoao** [comment]
Thank you for your great answer. I 'm looking forward to  the rewrite branch.

**Comment by albrow** [comment]
@xiaoao I have written a wiki page which provides more information about [how Zoom works under the hood](https://github.com/albrow/zoom/wiki/Under-the-Hood). I may add more information to it later, but I believe it is sufficient. I'm going to close this issue for now. Please let me know if you feel there is any information missing from the wiki page.
